# Welcome to Jekyll!
title: Kawano Yudai
email: 
description: >- # this means to ignore newlines until "baseurl:"
  B.Agr.
sub-description: Ruby / Java
baseurl: "" 
url: https://oriverk.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter: not_you_die 
github: oriverk
wantedly: 40069986
linkedin: yudai-k
lapras: CF9OBXY
qiita: OriverK
image: github-prtsc.png
google_analytics: UA-131793403-3

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-paginate
  - github-pages
  - jekyll-coffeescript

author:
  name: 'OriverK'
  url: https://qiita.com/OriverK

# Posts per page:
# paginate: 5
# paginate_path: '/blog/page:num'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
